#! /bin/sh
### BEGIN INIT INFO
# Provides:          autodetection
# Required-Start:    $network $local_fs $remote_fs $syslog $named
# Required-Stop:     $network $local_fs $remote_fs $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Autodetection service
# Description:       Responds to multicast messages to report hostname to RPiCCLV
### END INIT INFO

# Author: Darin Kinion <darin.kinion@revdaq.com>
#

case "$1" in
  start)
	echo "starting autodetect service"
	./usr/share/RPiCCLV/LV_Autodetect.py start
	;;
  stop)
	echo "stopping autodetect service"
	./usr/share/RPiCCLV/LV_Autodetect.py stop
	;;
  restart|reload)
	echo "restarting autodetect service"
	./usr/share/RPiCCLV/LV_Autodetect.py restart
	;;
  *)
	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
	echo "Usage: $SCRIPTNAME {start|stop|restart|reload}" >&2
	exit 3
	;;
esac

:
